### ISSUE TITLE
Infer `formattingToggle.affects` from the initial user configuration

### ISSUE THREAD

**Issue by vcarl** [Tom-Bonnike/vscode-formatting-toggle#49]
For months, I've been confused about why `formatOnPaste` kept getting re-enabled, and I've finally tracked it down to this extension. `affects` fixes the issue, but it took a lot of digging to find this as the cause.

It would be great if this behavior were either more prominently presented, or if this plugin could somehow infer what `affects` should be when it's installed.

**Comment by Tom-Bonnike** [comment]
Yeah, I went with `formatOnPaste` and `formatOnSave` as default because I thought that’s what most people would use, but you’re right, it should ideally not mess with the configuration.

It would probably be possible to infer the default based on what’s in the user’s config… I’ll try and see what I can do.

**Comment by Tom-Bonnike** [comment]
Meh, I documented `affects` and the extension now defaults to affecting all three formatting events. I think that’s good enough for now.
