### ISSUE TITLE
Toggle is not working. Error visible in the VSC console

### ISSUE THREAD

**Issue by kapalkat** [Tom-Bonnike/vscode-formatting-toggle#62]
Toggle is not working.

I get following error when trying to toggle:
ERR Unable to write to User Settings because formatOnSave is not a registered configuration.

**Comment by TrueWill** [comment]
Just a note that it took me quite a while to find this and figure out why the toggle was not working. As extension updates are typically automatic, it would be beneficial to notify users of the change (if it can't be made automatically) in large friendly letters. 😄 Otherwise people are likely to uninstall your fine extension. Thanks!

**Comment by wepsree** [comment]
Still getting OP's error after setting `"editor.formatOnSave": true` in `settings.json`
